spring:
  application:
    name: udemy-control-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/saul9402/udemy-control-config.git
          username: saul9402
          password: W8f!4%H%Y7xV5oqIW&
server:
  port: 8888
